### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by Pechenya2134** [Chase1803/Gloomy.cc#6]
![image](https://user-images.githubusercontent.com/67113647/169331279-ec4a2b65-e59b-4d06-a57f-812b7d91d12c.png)
black screen, menu doesnt open by any key

Doesn't work even after signature update

**Comment by Chase1803** [comment]
wdym signature update? also did you run as administrator and what windows 10 version?

**Comment by Pechenya2134** [comment]
> wdym signature update? also did you run as administrator and what windows 10 version?

i and my friend (which know more than me in cheats) updated lines in files: decryption.asm and main.cpp, new uworld, patterns, etc... Anyway that dont works, ur compiled version too. Windows 1909, runned as admin of course

**Comment by Pechenya2134** [comment]
![image](https://user-images.githubusercontent.com/67113647/169366343-9012a1fd-2d67-401b-acf3-d33ba56ecf48.png)

**Comment by Chase1803** [comment]
No idea eh, works fine for the other people and contributors here. Maybe you need to do some debugging on your own since it’s open source.. also have no idea what your friend means by “singed process” I think he meant sigged but that’s not relevant with this being open source and almost all the strings are being xor’d
